project_id = "xdyavylcmucjpueybdku"

[functions.generate-matiere-structure]
verify_jwt = true

[functions.anglais-practice-tutor]
verify_jwt = false

[functions.generate-quiz-final]
verify_jwt = false

[functions.suggest-youtube-videos]
verify_jwt = false

[functions.content-ai-assistant]
verify_jwt = true

[functions.generate-lesson-content]
verify_jwt = false

[functions.generate-lesson-section]
verify_jwt = true

[functions.generate-interactive-activities]
verify_jwt = true

[functions.generate-explanatory-images]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = false

[functions.math-ai-tutor]
verify_jwt = false

[functions.eric-chat]
verify_jwt = false

[functions.home-eric-chat]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.send-whatsapp-confirmation]
verify_jwt = false

[functions.send-test-email]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-password-reset-email]
verify_jwt = false

[functions.send-login-notification]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.passion-ai-tutor]
verify_jwt = false

[functions.francais-ai-tutor]
verify_jwt = false

[functions.spanish-practice-tutor]
verify_jwt = false

[functions.exam-tutor]
verify_jwt = false

[functions.parse-exam-text]
verify_jwt = true
