project_id = "xdyavylcmucjpueybdku"

[functions.math-ai-tutor]
verify_jwt = false

[functions.eric-chat]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.send-whatsapp-confirmation]
verify_jwt = false

[functions.send-test-email]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-password-reset-email]
verify_jwt = false

[functions.send-login-notification]
verify_jwt = false