// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp, auth } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.58.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-my-profile.ts
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Get the signed-in student's profile: name, academic grade, gold earned, streak and exam stats.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select(
      "full_name, nickname, academic_grade, school, gold_earned, current_streak, longest_streak, exams_completed, best_exam_score_percent"
    ).eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No profile found." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/list-subjects.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";
var list_subjects_default = defineTool2({
  name: "list_subjects",
  title: "List subjects",
  description: "List the school subjects (mati\xE8res) available on Edupreneurs, optionally filtered by academic grade code (7AF, 8AF, 9AF, NS1-NS4).",
  inputSchema: {
    grade_level: z.string().trim().optional().describe("Academic grade code, e.g. 9AF or NS4. Omit for all grades.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ grade_level }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("subjects").select("id, name, slug, grade_level, series, lesson_count").order("name");
    if (grade_level) query = query.eq("grade_level", grade_level);
    const { data, error } = await query.limit(100);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { subjects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-lessons.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_lessons_default = defineTool3({
  name: "list_lessons",
  title: "List lessons",
  description: "List published lessons, optionally filtered by subject id, academic grade, or a title search term.",
  inputSchema: {
    subject_id: z2.string().uuid().optional().describe("Subject id from list_subjects."),
    grade_level: z2.string().trim().optional().describe("Academic grade code, e.g. NS2."),
    search: z2.string().trim().min(1).optional().describe("Search text matched against lesson titles."),
    limit: z2.number().int().min(1).max(50).optional().describe("Max lessons to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ subject_id, grade_level, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("lessons").select("id, title, slug, subject_id, grade_level, order_index, mois").eq("is_published", true).order("order_index", { ascending: true });
    if (subject_id) query = query.eq("subject_id", subject_id);
    if (grade_level) query = query.eq("grade_level", grade_level);
    if (search) query = query.ilike("title", `%${search}%`);
    const { data, error } = await query.limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { lessons: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-lesson.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var MAX_SECTION_CHARS = 4e3;
function trim(value) {
  if (typeof value !== "string") return null;
  return value.length > MAX_SECTION_CHARS ? `${value.slice(0, MAX_SECTION_CHARS)}\u2026` : value;
}
var get_lesson_default = defineTool4({
  name: "get_lesson",
  title: "Get lesson",
  description: "Get the full text of one published lesson by its slug: objective, introduction, content and worked examples.",
  inputSchema: {
    slug: z3.string().trim().min(1).describe("Lesson slug from list_lessons.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("lessons").select("id, title, slug, grade_level, objectif, introduction, contenu, exemples_exercices, references, youtube_url").eq("slug", slug).eq("is_published", true).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No published lesson with slug "${slug}".` }], isError: true };
    const lesson = {
      id: data.id,
      title: data.title,
      slug: data.slug,
      grade_level: data.grade_level,
      objectif: trim(data.objectif),
      introduction: trim(data.introduction),
      contenu: trim(data.contenu),
      exemples_exercices: trim(data.exemples_exercices),
      references: data.references,
      youtube_url: data.youtube_url
    };
    return {
      content: [{ type: "text", text: JSON.stringify(lesson) }],
      structuredContent: { lesson }
    };
  }
});

// src/lib/mcp/tools/list-my-completed-lessons.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_my_completed_lessons_default = defineTool5({
  name: "list_my_completed_lessons",
  title: "List my completed lessons",
  description: "List the lessons the signed-in student has completed, most recent first, with their quiz scores.",
  inputSchema: {
    limit: z4.number().int().min(1).max(100).optional().describe("Max rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("lesson_completions").select("lesson_slug, subject, score, completed_at").eq("user_id", ctx.getUserId()).order("completed_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { completions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-word-of-the-day.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_word_of_the_day_default = defineTool6({
  name: "get_word_of_the_day",
  title: "Get word of the day",
  description: "Get the current active 'Mot du Jour' vocabulary word with its phonetic, definition and example sentence.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("daily_words").select("word, phonetic, part_of_speech, definition, example, category, difficulty_level, audio_url").eq("is_active", true).order("display_order", { ascending: false }).limit(1).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No active word of the day." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { word: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xdyavylcmucjpueybdku";
var mcp_default = defineMcp({
  name: "edupreneurs-haiti-ai",
  title: "edupreneurs-haiti-ai",
  version: "0.1.0",
  instructions: "Tools for Edupreneurs Haiti, a French-language learning platform for Haitian students. Use list_subjects and list_lessons to browse the curriculum, get_lesson to read a lesson, get_my_profile and list_my_completed_lessons for the signed-in student's progress, and get_word_of_the_day for the daily vocabulary word.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_profile_default, list_subjects_default, list_lessons_default, get_lesson_default, list_my_completed_lessons_default, get_word_of_the_day_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
